config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:update]
  root to: 'welcome#index'
  get 'about' => 'welcome#about'
  get 'services' => 'welcome#pricing'

  resources :subscribers, only: [:new, :create]

  resources :journals, only: [] do
    resources :entries
  end

  resources :boxes do
    resources :journals, except: [:show]
    resources :pictures
    resources :recipients, only: [:create, :update, :destroy]
  end

  get :send_recipient_confirmation, to: 'recipients#send_recipient_confirmation', as: :send_recipient_confirmation
end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id         :integer          not null, primary key
#  body       :text
#  journal_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  subject    :string
#

class Entry < ActiveRecord::Base
  belongs_to :journal

  default_scope { order('created_at DESC') }

  validates :body, presence: true
  validates :subject, presence: true
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @journal = Journal.find(params[:journal_id])
    #@entries = Entry.all
    @entrys = @journal.entries
  end

  def show
    @journal = Journal.find(params[:journal_id])
    @entry = Entry.find(params[:id])
  end

  def new
    @journal = Journal.find(params[:journal_id])
    @entry = Entry.new
  end

  def create
    @journal = Journal.find(params[:journal_id])
    @entry = Entry.new(params.require(:entry).permit(:subject, :body))
    @entry.journal = @journal
      if @entry.save
        flash[:notice] = "You have successfully saved your journal entry."
        redirect_to [@journal, @entry]
      else
        flash[:error] = "We were not able to save your journal entry. Please try again."
        render :new
      end
  end

  def edit
    @journal = Journal.find(params[:journal_id])
    @entry = Entry.find(params[:id])
  end

  def update
    @journal = Journal.find(params[:journal_id])
    @entry = Entry.find(params[:id])
    if @entry.update_attributes(params.require(:entry).permit(:subject, :body))
      flash[:notice] = "You have updated your entry successfully."
      redirect_to @entry
    else
      flash[:error] = "We have encountered a problem updating your entry. Please try again."
      render :edit
    end
  end

  def destroy
    @journal = Journal.find(params[:box_id])
    @entry = Entry.find(params[:id])

    if @entry.destroy
      flash[:notice] = "Your entry was removed successfully."
      redirect_to box_journals_path
    else
      flash[:error] = "There was an error deleting the journal. Please try again."
      render :show
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for [journal, entry] do |f| %>
  <div class="form-group">
    <%= f.label :subject %>
    <%= f.text_field :subject, class: 'form-control', placeholder: "What's the subject?" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', placeholder: "Type away..." %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Cancel", journal_entries_path , class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Edit your Entry</h1>

<div class="row well edit_back">
  <div class="col-md-3" id="journal_directions">
    <h3>Guidelines for Entry</h3>
    <h4><ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul></h4>
  </div>
  <div class="col-md-8 col-md-offset-1 well">
    <%= render partial: 'form', locals: { journal: @journal, entry: @entry} %>
  </div>
</div>

app/views/entries/index.html.erb
<h1>Journal Entries</h1>
<div class="row well journal_index">
  <div class="col-md-10 col-md-offset-1">
  <%= link_to "Create Entry", new_journal_entry_path, class: 'btn btn-primary btn-xs' %>
  <%= link_to "All Journals", box_journals_path(@journal.box), class: 'btn btn-primary btn-xs' %>
  <% @entrys.each do |entry| %>
    <div class="media well well-sm">
      <div class="media-body">
        <h4 class="media-heading">
          <%= entry.subject%>:
          <%= link_to truncate(entry.body), [@journal, entry] %>
        </h4>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/entries/new.html.erb
<h1>Your New Entry</h1>

 <div class="row well journal_index">
   <div class="col-md-4" id="journal_directions">
     <h4>Guidelines for entry</h4>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8 well">
     <%= render partial: 'form', locals: { journal: @journal, entry: @entry } %>
   </div>
 </div>

app/views/entries/show.html.erb
<h1><%= @entry.subject %></h1>
<div class="row well journal_index">
    <div class="col-md-10 col-md-offset-1">
    <%= link_to "All Journals", box_journals_path(@journal.box), class: 'btn btn-primary btn-xs' %>
    <%= link_to "Entries", journal_entries_path(@journal), class: 'btn btn-primary btn-xs' %>

    <div class="media well">
      <div class="media-body">
        <h4 class="media-heading">
          <%= @entry.body %>
          <h6 class="col-md-9"><%= link_to "Edit Entry", edit_journal_entry_path %></h6>
          <h6 class="col-md-3"><%= link_to "Delete Entry", [@journal, @entry], method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: 'Are you sure you want to delete this entry?' } %></h6>
        </h4>
      </div>
    </div>
    </div>
</div>