config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:update]
  root to: 'welcome#index'
  get 'about' => 'welcome#about'
  get 'services' => 'welcome#pricing'

  resources :subscribers, only: [:new, :create]

  resources :journals, only: [] do
    resources :entries
  end

  resources :boxes do
    resources :journals, except: [:show]
    resources :pictures
    resources :recipients, only: [:create, :update, :destroy]
  end

  get :send_recipient_confirmation, to: 'recipients#send_recipient_confirmation', as: :send_recipient_confirmation
end

app/models/box.rb
# == Schema Information
#
# Table name: boxes
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Box < ActiveRecord::Base
  belongs_to :user
  has_many :pictures, dependent: :destroy
  has_many :journals, dependent: :destroy
  has_many :recipients, dependent: :destroy
  has_many :recipient_users, through: :recipients, source: :user

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
before_action :authenticate_user!
  def index
    @boxes = policy_scope(Box)
    authorize @boxes
    @received_boxes = current_user.received_boxes
  end

  def show
    @box = Box.find(params[:id])
    @recipient = Recipient.new
    @recipients = @box.recipients
  end

  def new
    @box = Box.new
    authorize @box
  end

  def create
  @box = Box.new(params.require(:box).permit(:title, :description))
  @box.user = current_user #this allows us to create user-specific boxes
  authorize @box
    if @box.save
      flash[:notice] = "You successfully built your first trove. Time to fill it with memories."
      redirect_to @box
    else
      flash[:error] = "We were not able to build your trove successfully. Please try again."
      render :new
    end
  end

  def edit
    @box = Box.find(params[:id])
  end

  def update
    @box = Box.find(params[:id])
    if @box.update_attributes(params.require(:box).permit(:title, :description))
      flash[:notice] = "You have update your trove successfully."
      redirect_to @box
    else
      flash[:error] = "We have encountered a problem updating your trove. Please try again."
      render :edit
    end
  end

  def destroy
    @box = Box.find(params[:id])

    if @box.destroy
      flash[:notice] = "\"#{@box.title}\" was removed successfully."
      redirect_to boxes_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end

end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.erb
<%= form_for box do |f| %>
  <% if box.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(box.errors.count, "error") %>.</h4>
      <ul>
        <% box.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(box.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Name your trove" %>
  <% end %>
  <%= form_group_tag(box.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Please provide a description of your trove contents" %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Cancel", boxes_path , class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/boxes/_rec_form.html.erb
<%= form_for [box, recipient] do |f| %>
  <% if recipient.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(recipient.errors.count, "error") %>.</h4>
      <ul>
        <% recipient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(recipient.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Name of recipient" %>
  <% end %>
  <%= form_group_tag(recipient.errors[:email]) do %>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', placeholder: "Please provide email" %>
  <% end %>
  <%= form_group_tag(recipient.errors[:DOB]) do %>
    <%= f.label "Date of Birth" %>
    <%= f.date_select :DOB, use_short_month: true, start_year: 1915, end_year: 2015 %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Edit your Trove</h1>

<div class="row well trove_main">
  <div class="col-md-3" id="journal_directions">
    <h3>Guidelines for troves</h3>
    <h4><ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul></h4>
  </div>
  <div class="col-md-8 col-md-offset-1 well">
    <%= render partial: 'form', locals: { box: @box } %>
  </div>
</div>

app/views/boxes/index.html.erb
<h1>Your Troves</h1>
<div class="row well trove_main">
  <div class="col-md-4">
    <h4 id="trove_directions">This is where you begin the creation of your trove. After the trove is created, you can begin to add itmes to it as well as assign recipients to your trove.</h4>
    <%= link_to "Create Trove", new_box_path, class: 'btn btn-primary btn-xs' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <h2>Boxes</h2>
    <% @boxes.each do |box| %>
      <div class="row media well well-sm">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to box.title, box, class: 'col-xs-9 col-md-9' %>
            <%= link_to "Delete Trove", box, method: :delete, class: 'btn btn-danger btn-xs col-xs-3 col-md-2 col-md-offset-1', data: { confirm: 'Are you sure you want to delete this Trove?' } %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-7 col-md-offset-1">
    <h2>Received Boxes</h2>
    <% @received_boxes.each do |box| %>
      <div class="row media well well-sm">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to box.title, box, class: 'col-xs-9 col-md-9' %>
            <%= link_to "Delete Trove", box, method: :delete, class: 'btn btn-danger btn-xs col-xs-3 col-md-2 col-md-offset-1', data: { confirm: 'Are you sure you want to delete this Trove?' } %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/boxes/new.html.erb
<h1>Your New Trove</h1>

 <div class="row well trove_main">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8 well">
     <%= render partial: 'form', locals: { box: @box } %>
   </div>
 </div>

app/views/boxes/show.html.erb
<h1><%= @box.description %></h1>

<div class="row well boxes img-responsive" id="trove_show">
  <div class="col-md-2">
    <h4 id="trove_directions">Here you can access the items in the trove. You can also add or remove recipients from the trove as well as view the list of recipients.</h4>
    <br>
    <%= link_to "Edit", edit_box_path, class: 'btn btn-primary btn-sm' %>
    <%= link_to "Troves", boxes_path , class: 'btn btn-primary btn-sm' %>
  </div>

  <div class="col-md-4 col-md-offset-1 well well-sm list">
    <p>Description: <%= @box.description %></p>
      <% if current_user.admin? || current_user.premium? %>
      <div class="btn-group" role="group">
        <%= link_to "Journals", box_journals_path(@box), class: 'btn btn-info btn-sm' %>
        <%= link_to "Video", '#', class: 'btn btn-info btn-sm' %>
        <%= link_to "Pictures", box_pictures_path(@box), class: 'btn btn-info btn-sm' %>
        <%= link_to "Audio", '#', class: 'btn btn-info btn-sm' %>
      </div>
      <% end %>
      <% if current_user.basic? %>
      <div class="btn-group" role="group">
        <%= link_to "Journals", box_journals_path(@box), class: 'btn btn-info btn-sm' %>
        <%= link_to "Pictures", box_pictures_path(@box), class: 'btn btn-info btn-sm' %>
      </div>
      <% end %>

      <h5 class="well">
        Recipient List: <br>
        <% @recipients.each do |recipient| %>
          <div class="media">
            <div class="media-body">
              <div class="media-heading">
                <%= recipient.name %><br>
                | <%= link_to "Delete", [@box, recipient], method: :delete %> |
                <%= link_to "Confirm Recipient", :controller => "recipients", :action => "send_recipient_confirmation", :id => recipient.id %> |
              </div>
            </div>
          </div>
        <% end %>
      </h5>
  </div>

  <div class="col-md-4 col-md-offset-1 well well-sm list">
    <h5>Add Recipients Here:</h5>
    <%= render partial: 'rec_form', locals: { box: @box, recipient: @recipient } %>
  </div>
</div>