config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:update]
  root to: 'welcome#index'
  get 'about' => 'welcome#about'
  get 'services' => 'welcome#pricing'

  resources :subscribers, only: [:new, :create]

  resources :journals, only: [] do
    resources :entries
  end

  resources :boxes do
    resources :journals, except: [:show]
    resources :pictures
    resources :recipients, only: [:create, :update, :destroy]
  end

  get :send_recipient_confirmation, to: 'recipients#send_recipient_confirmation', as: :send_recipient_confirmation
end

app/models/journal.rb
# == Schema Information
#
# Table name: journals
#
#  id         :integer          not null, primary key
#  title      :string
#  box_id     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Journal < ActiveRecord::Base
  belongs_to :box
  has_many :entries, dependent: :destroy

  validates :title, presence: true
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
before_action :authenticate_user!
  def index
    @box = Box.find(params[:box_id])
    @jrnl4box = @box.journals
  end

  def show #can this be done differently?
    @box = Box.find(params[:box_id])
    @journal = Journal.find(params[:id])
  end

  def new
    @box = Box.find(params[:box_id])
    @journal = Journal.new
  end

  def create
    @box = Box.find(params[:box_id])
    @journal = Journal.new(params.require(:journal).permit(:title, :entry))
    @journal.box = @box
    if @journal.save
      flash[:notice] = "You successfully started your Journal"
      redirect_to box_journals_path
    else
      flash[:error] = "We had a problem starting your journal. Please try again."
      render :new
    end
  end

  def edit
    @box = Box.find(params[:box_id])
    @journal = Journal.find(params[:id])
  end

  def update
    @box = Box.find(params[:box_id])
    @journal = Journal.find(params[:id])
    if @journal.update_attributes(params.require(:journal).permit(:title, :entry))
      flash[:notice] = "You have updated your journal successfully"
      redirect_to box_journals_path
    else
      flash[:error] = "We had a problem updating your journal. Please try again."
      render :edit
    end
  end

  def destroy
    @box = Box.find(params[:box_id])
    @journal = Journal.find(params[:id])

    if @journal.destroy
      flash[:notice] = "\"#{@journal.title}\" was removed successfully."
      redirect_to box_journals_path
    else
      flash[:error] = "There was an error deleting the journal. Please try again."
      render :show
    end
  end
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/journals/_form.html.erb
<%= form_for [box, journal] do |f| %>
  <% if journal.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(journal.errors.count, "error") %>.</h4>
      <ul>
        <% journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(journal.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Name your journal" %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Cancel", box_journals_path , class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/journals/edit.html.erb
<h1>Edit your Journal</h1>

<div class="row well edit_back">
  <div class="col-md-3" id="journal_directions">
    <h3>Guidelines for Journal</h3>
    <h4><ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul></h4>
  </div>
  <div class="col-md-8 col-md-offset-1 well">
    <%= render partial: 'form', locals: { box: @box, journal: @journal} %>
  </div>
</div>

app/views/journals/index.html.erb
<h1>Your Journals</h1>
<div class="row well journal_index">
  <div class="col-md-3">
    <h3 id="trove_directions">This is where you can curate your journals for a given trove. You can create journals as well as continue to develop journals that you already have.</h3>
    <%= link_to "Create Journal", new_box_journal_path, class: 'btn btn-primary btn-xs' %>
    <%= link_to "Trove", box_path(@box), class: 'btn btn-primary btn-xs' %>
  </div>

  <div class="col-md-7 col-md-offset-1">
    <% @jrnl4box.each do |journal| %>
      <div class="row media well well-sm">
        <div class="media-body">
          <h4 class="media-heading">
            <%= journal.title %>
              <h6 class="col-xs-9 col-md-9"><%= link_to "New Entry", new_journal_entry_path(journal, @entry)%> |
              <%= link_to "View Entries", journal_entries_path(journal)%> |
              <%= link_to "Edit Journal", edit_box_journal_path(@box, journal)%></h6>
              <h6 class="col-xs-3 col-md-2 col-md-offset-1"><%= link_to "Delete", [@box, journal], method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: 'Are you sure you want to delete this journal?' } %></h6>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/journals/new.html.erb
<h1>Your New Journal</h1>

 <div class="row well boxes">
   <div class="col-md-4" id="journal_directions">
     <h4>Consider the following while developing your journal:</h4>
     <ul>
       <li>Will this journal be private or shared with others</li>
       <li>When do you plan to have this journal delivered?</li>
       <li>What purpose will this journal serve?</li>
     </ul>
   </div>
   <div class="col-md-8 well">
     <%= render partial: 'form', locals: { box: @box, journal: @journal} %>
   </div>
 </div>

app/views/journals/show.html.erb
<!--not using this page
<h1><%= @journal.title %></h1>

<div class="row well journal_index">
  <div class="col-md-7 col-md-offset-1 well">
    <p><%= @journal.title %></p>
      <div class="btn-group" role="group">
        <%= link_to "New Entry", new_journal_entry_path(@journal, @entry), class: 'btn btn-info btn-xs' %>
        <%= link_to "View Entries", journal_entries_path(@journal), class: 'btn btn-info btn-xs' %>
      </div>
  </div>
  <div class="col-md-3 col-md-offset-1">
      <%= link_to "Edit", edit_box_journal_path(@box, @journal), class: 'btn btn-primary btn-sm' %>
      <%= link_to "Journals", box_journals_path(@box) , class: 'btn btn-primary btn-sm' %>
  </div>
</div>
-->