config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:update]
  root to: 'welcome#index'
  get 'about' => 'welcome#about'
  get 'services' => 'welcome#pricing'

  resources :subscribers, only: [:new, :create]

  resources :journals, only: [] do
    resources :entries
  end

  resources :boxes do
    resources :journals, except: [:show]
    resources :pictures
    resources :recipients, only: [:create, :update, :destroy]
  end

  get :send_recipient_confirmation, to: 'recipients#send_recipient_confirmation', as: :send_recipient_confirmation
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:error] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "myApp", root_path, class: 'navbar-brand' %>
    </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Services", services_path %></li>
      <% if user_signed_in? %> <!--will make this only visible when logged in-->
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Shortcuts<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Troves", boxes_path %></li>
            <li><%= link_to "Profile", edit_user_registration_path %></li>
          </ul>
      </li>
      <% end %>

      <div class="navbar-text navbar-right">
        <% if current_user %>
        Hello <%= current_user.name %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
        <%= link_to "Sign In", new_user_session_path %> or
        <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fp1</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>
  <footer class="footer navbar-fixed-bottom">
    <div class="container footer_cont">
      <p class="text-muted">&copy TechieDodo -- This Bird will Soar Again...</p>
    </div>
  </footer>
</body>
</html>